/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generate a random 32-byte key for encryption */
export declare function generateKey(): Buffer
/** Generate a random 24-byte nonce for XChaCha20-Poly1305 */
export declare function generateNonce(): Buffer
/**
 * Encrypt a data chunk using XChaCha20-Poly1305
 *
 * # Arguments
 * * `data` - The plaintext data to encrypt
 * * `key` - 32-byte encryption key
 * * `nonce` - 24-byte nonce (must be unique for each encryption with the same key)
 *
 * # Returns
 * Encrypted data (ciphertext + 16-byte authentication tag)
 */
export declare function encryptChunk(data: Buffer, key: Buffer, nonce: Buffer): Buffer
/**
 * Decrypt a data chunk using XChaCha20-Poly1305
 *
 * # Arguments
 * * `data` - The encrypted data (ciphertext + auth tag)
 * * `key` - 32-byte encryption key (same as used for encryption)
 * * `nonce` - 24-byte nonce (same as used for encryption)
 *
 * # Returns
 * Decrypted plaintext data
 */
export declare function decryptChunk(data: Buffer, key: Buffer, nonce: Buffer): Buffer
/**
 * Hash a data chunk using BLAKE3
 *
 * # Arguments
 * * `data` - The data to hash
 *
 * # Returns
 * 32-byte hash digest
 */
export declare function hashChunk(data: Buffer): Buffer
/**
 * Hash a data chunk with a key (keyed hash / MAC)
 *
 * # Arguments
 * * `data` - The data to hash
 * * `key` - 32-byte key for keyed hashing
 *
 * # Returns
 * 32-byte keyed hash
 */
export declare function hashChunkKeyed(data: Buffer, key: Buffer): Buffer
/**
 * Derive a key from a password using BLAKE3 KDF
 *
 * # Arguments
 * * `password` - The password to derive from
 * * `salt` - Salt for key derivation
 * * `context` - Context string for domain separation
 *
 * # Returns
 * 32-byte derived key
 */
export declare function deriveKey(password: string, salt: Buffer, context: string): Buffer
