# ClovaLink Podman Development Environment
# IMPORTANT: Use "podman compose down" (WITHOUT -v) to keep database data
# Use "podman compose down -v" only if you want to reset everything including database

services:
  app:
    image: node:20-bullseye
    working_dir: /app
    command: sh -c "if [ ! -d 'node_modules' ] || [ ! -f 'node_modules/.installed' ]; then npm install && touch node_modules/.installed; fi && npx prisma db push --skip-generate && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clovalink?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - NODE_ENV=development
      - UPLOAD_DIR=/app/uploads
      - WATCHPACK_POLLING=true
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - .:/app:delegated
      - node_modules_cache:/app/node_modules
      - ./uploads:/app/uploads:delegated
      - next_cache:/app/.next
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clovalink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_modules_cache:
  next_cache:

